### ISSUE TITLE
Planning to releast the pre-trained weights ? 

### ISSUE THREAD

**Issue by Bala93** [McJackTang/MMPD_rPPG_dataset#10]

**Comment by McJackTang** [comment]
The pretrained model could be seen at [rppg-Toolbox_MMPD/final_model_release](https://github.com/McJackTang/MMPD_rPPG_dataset/tree/main/rppg-Toolbox_MMPD/final_model_release)

**Comment by Bala93** [comment]
Do we have pre-trained model weights on MMPD_rPPG_dataset ?

**Comment by McJackTang** [comment]
We are working on that and we will release that with publications.

**Comment by Bala93** [comment]
Sure. Thanks for your reply.
