### ISSUE TITLE
关于数据延迟

### ISSUE THREAD

**Issue by 408550969** [McJackTang/MMPD_rPPG_dataset#15]
你好，我现在采的数据，如果人为往后延500ms，发现模型就无法收敛了，MAE提高到了10几，而不延状态下的MAE是0.几。我对RPPG方向不是很熟悉，请问模型的训练对延迟很敏感吗？一般延迟要控制在多少以内才合适？

**Comment by McJackTang** [comment]
是的，延迟越低越好

**Comment by 408550969** [comment]
谢谢
