### ISSUE TITLE
How to restore .mat formatted data to the original .avi or .mp4 video files？

### ISSUE THREAD

**Issue by JasonYpro** [McJackTang/MMPD_rPPG_dataset#18]
Thank you very much for providing the dataset. How can I restore .mat formatted data to the original .avi or .mp4 video files?

**Comment by McJackTang** [comment]
If you already downloaded MMPD dataset with agreement, you can easily read it by the following code:
```
import scipy.io as sio
f = sio.loadmat('p1_0.mat')
print(f.keys())
```
Then you can get the video (shape:  [t, w, h, c]) and write it as avi or mp4 file. Please note that incorrect encode method may damage the quality of the dataset if you want to change it back to video.

**Comment by JasonYpro** [comment]
> If you already downloaded MMPD dataset with agreement, you can easily read it by the following code:
> 
> ```
> import scipy.io as sio
> f = sio.loadmat('p1_0.mat')
> print(f.keys())
> ```
> 
> Then you can get the video (shape: [t, w, h, c]) and write it as avi or mp4 file. Please note that incorrect encode method may damage the quality of the dataset if you want to change it back to video.

What encoding should I use for the MMPD dataset to ensure no loss?

**Comment by McJackTang** [comment]
Could you share your motivation to get the mp4/avi so that we could offer better suggestions?

> > If you already downloaded MMPD dataset with agreement, you can easily read it by the following code:
> > ```
> > import scipy.io as sio
> > f = sio.loadmat('p1_0.mat')
> > print(f.keys())
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then you can get the video (shape: [t, w, h, c]) and write it as avi or mp4 file. Please note that incorrect encode method may damage the quality of the dataset if you want to change it back to video.
> 
> What encoding should I use for the MMPD dataset to ensure no loss?

**Comment by McJackTang** [comment]
If no more questions or replies, I will close this issue due to the time limit.
