### ISSUE TITLE
关于subject 24肤色分类的问题

### ISSUE THREAD

**Issue by ZacheryZhang** [McJackTang/MMPD_rPPG_dataset#19]
在检查标签时，发现subject 24肤色标签出现了不匹配，p24_0的Fitzpatrick Skin Type是4，其余的为3，可否阐明该问题？

**Comment by McJackTang** [comment]
您的反馈已收到。我们会核查人工标签的准确性，如果有误标注会在后续更新数据集。

> p24_0

**Comment by McJackTang** [comment]
我们检查了原始数据，肤色标签应该是3，如有做分类研究的可以自行更新，如果使用全集训练测试则不受影响。
